require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Naming/RescuedExceptionsVariableName:
  Enabled: Yes
  PreferredName: error

Style/Documentation:
  Enabled: No
