version: '3'

services:
  rethinkdb:
    image: rethinkdb:2.4

  gem:
    build: .
    image: nobrainerorm/nobrainer:latest
    depends_on:
      - rethinkdb
    environment:
      - RUBY_ENV=test
      # The nobrainer Rspec config expects the DB_HOST variable
      # (see spec/spec_helper.rb), that's why we aren't setting the RDB_HOST env
      # variable here.
      - DB_HOST=rethinkdb
    volumes:
      - .:/gem
