on:
   push:
     branches:
       - master
   pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.2
            rails: 4
            eventmachine: false
          - ruby: 2.3
            rails: 5
            eventmachine: false
          - ruby: 2.3
            rails: 5
            eventmachine: true
          - ruby: 2.6
            rails: 6
            eventmachine: true
          - ruby: 2.6
            rails: 6
            eventmachine: false
          - ruby: 2.7
            rails: 6
            eventmachine: false
          - ruby: 2.7
            rails: 6
            eventmachine: true
          - ruby: 3
            rails: 6
            eventmachine: false
          - ruby: 3
            rails: 6
            eventmachine: true
          - ruby: 3
            rails: 7
            eventmachine: true
          - ruby: 3
            rails: 7
            eventmachine: false
          - ruby: 3
            rails: 8
            eventmachine: false
          - ruby: 3
            rails: 8
            eventmachine: true
    runs-on: ubuntu-latest
    name: RSpec suite (Ruby ${{ matrix.ruby }}/Rails ${{ matrix.rails }}/EM ${{ matrix.eventmachine }})
    env:
      EM: ${{ matrix.eventmachine }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      EARTHLY_RAILS_VERSION: ${{ matrix.rails }}
      EARTHLY_RUBY_VERSION: ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v3
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.14/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --ci --allow-privileged +rspec --EARTHLY_RUBY_VERSION=$EARTHLY_RUBY_VERSION --EARTHLY_RAILS_VERSION=$EARTHLY_RAILS_VERSION --EM=$EM
